chore(ci): dont attempt to parse nonexistent message

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -206,32 +206,27 @@ jobs:
           RETRY_AFTER_SECONDS=30
           MAX_RETRY_ATTEMPTS=$(($RETRY_MINUTES*60/$RETRY_AFTER_SECONDS))
           for (( i = 0; i < $MAX_RETRY_ATTEMPTS; i++ )); do
-          NOTARIZATION_STATUS_JSON=$(xcrun altool \
-          --notarization-info ${{ steps.parse_notarize.outputs.REQUEST_UUID }} \
-          --username ${{ env.APPLE_USERNAME }} \
-          --password ${{ secrets.MACOS_NOTARIZATION_PASSWORD }} \
-          --output-format json)
-          NOTARIZATION_STATUS=$(cat <<EOM | jq -r -e '.["notarization-info"].Status'
-          $NOTARIZATION_STATUS_JSON
-          EOM
-          )
-          NOTARIZATION_STATUS_MESSAGE=$(cat <<EOM | jq -r -e '.["notarization-info"]."Status Message"'
-          $NOTARIZATION_STATUS_JSON
-          EOM
-          )
-          if [ $NOTARIZATION_STATUS == "success" ]; then
-            echo "::debug::$NOTARIZATION_STATUS_MESSAGE"
-            exit 0
-          elif [ $NOTARIZATION_STATUS == "in progress" ]; then
-            echo "::debug::$NOTARIZATION_STATUS_MESSAGE"
-            echo "::debug::Trying again after $RETRY_AFTER_SECONDS"
-            sleep $RETRY_AFTER_SECONDS
-          else
-            echo "::debug::Invalid notarization status"
-            echo "::debug::$NOTARIZATION_STATUS"
-            echo "::debug::$NOTARIZATION_STATUS_MESSAGE"
-            exit 1
-          fi
+            NOTARIZATION_STATUS_JSON=$(xcrun altool \
+            --notarization-info ${{ steps.parse_notarize.outputs.REQUEST_UUID }} \
+            --username ${{ env.APPLE_USERNAME }} \
+            --password ${{ secrets.MACOS_NOTARIZATION_PASSWORD }} \
+            --output-format json)
+            NOTARIZATION_STATUS=$(cat <<EOM | jq -r -e '.["notarization-info"].Status'
+            $NOTARIZATION_STATUS_JSON
+            EOM
+            )
+            if [ $NOTARIZATION_STATUS == "success" ]; then
+              echo "Notarization successful."
+              exit 0
+            elif [ $NOTARIZATION_STATUS == "in progress" ]; then
+              echo "::debug::$NOTARIZATION_STATUS_MESSAGE"
+              echo "::debug::Trying again after $RETRY_AFTER_SECONDS"
+              sleep $RETRY_AFTER_SECONDS
+            else
+              echo "::debug::Invalid notarization status"
+              echo "::debug::$NOTARIZATION_STATUS_JSON"
+              exit 1
+            fi
           done
           echo "::debug::Notarization timed out after $RETRY_MINUTES minutes."
           exit 1
