feat: cargo xtask (#562)
Co-authored-by: Stephen Barlow <stephen@apollographql.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -31,15 +31,19 @@ jobs:
           - build: linux-gnu
             os: ubuntu-16.04
             rust: stable
+            target: x86_64-unknown-linux-gnu
           - build: linux-musl
             os: ubuntu-latest
             rust: stable
+            target: x86_64-unknown-linux-musl
           - build: macos
             os: macos-latest
             rust: stable
+            target: x86_64-apple-darwin
           - build: windows
             os: windows-latest
             rust: stable
+            target: x86_64-pc-windows-msvc
 
     outputs:
       version: ${{ steps.get_version.outputs.version }}
@@ -79,34 +83,14 @@ jobs:
           sudo apt update
           sudo apt install musl-tools
 
-      - name: Build (GNU Linux)
-        if: matrix.build == 'linux-gnu'
-        run: |
-          rustup target add ${{ env.LINUX_GNU_TARGET }}
-          cargo build --release --target ${{ env.LINUX_GNU_TARGET }}
-        env:
-          OPENSSL_STATIC: 1
+      - name: Install Rust toolchain
+        run: rustup target add ${{ matrix.target }}
 
-      - name: Build (MUSL Linux)
-        if: matrix.build == 'linux-musl'
-        run: |
-          rustup target add ${{ env.LINUX_MUSL_TARGET }}
-          cargo build --release --no-default-features --target ${{ env.LINUX_MUSL_TARGET }}
-        env:
-          OPENSSL_STATIC: 1 # statically link OpenSSL
-          
-      - name: Build (MacOS)
-        if: matrix.build == 'macos'
-        run: cargo build --release
-        env:
-          OPENSSL_DIR: /usr/local/opt/openssl@1.1 # don't use system install of LibreSSL
-          OPENSSL_STATIC: 1 # statically link OpenSSL
-        
-      - name: Build (Windows)
-        if: matrix.build == 'windows'
-        run: cargo build --release
-        env:
-          RUSTFLAGS: -Ctarget-feature=+crt-static # fully static build
+      - name: Test
+        run: cargo xtask test --verbose --target ${{ matrix.target }}
+
+      - name: Build
+        run: cargo xtask dist --verbose --target ${{ matrix.target }}
 
       - name: Populate artifact directory
         shell: bash
@@ -114,29 +98,15 @@ jobs:
           mkdir ${{ env.RELEASE_DIR }} dist
           mv ${{ env.RELEASE_ADDS }} ./dist
 
-      - name: Move binary to dist (MacOS)
-        if: matrix.build == 'macos'
+      - name: Move binary to dist
+        if: matrix.build != 'windows' 
         shell: bash
-        run: mv ./target/release/${{ env.RELEASE_BIN }} ./dist/${{ env.RELEASE_BIN }}
+        run: mv ./target/${{ matrix.target }}/release/${{ env.RELEASE_BIN }} ./dist/${{ env.RELEASE_BIN }}
 
-      - name: Create tarball (GNU Linux)
-        if: matrix.build == 'linux-gnu'
-        run: |
-          mv ./target/${{ env.LINUX_GNU_TARGET }}/release/${{ env.RELEASE_BIN }} ./dist/${{ env.RELEASE_BIN }}
-          7z a -ttar -so -an ./dist | 7z a -si ./${{ env.RELEASE_DIR }}/${{ env.RELEASE_BIN }}-${{ steps.get_version.outputs.version }}-${{ env.LINUX_GNU_TARGET }}.tar.gz
-
-      - name: Create tarball (MUSL Linux)
-        if: matrix.build == 'linux-musl'
-        run: |
-          mv ./target/${{ env.LINUX_MUSL_TARGET }}/release/${{ env.RELEASE_BIN }} ./dist/${{ env.RELEASE_BIN }}
-          7z a -ttar -so -an ./dist | 7z a -si ./${{ env.RELEASE_DIR }}/${{ env.RELEASE_BIN }}-${{ steps.get_version.outputs.version }}-${{ env.LINUX_MUSL_TARGET }}.tar.gz
-
-      - name: Create tarball (Windows)
-        if: matrix.build == 'windows'
+      - name: Move binary to dist (Windows)
+        if: matrix.build == 'windows' 
         shell: bash
-        run: |
-          mv ./target/release/${{ env.RELEASE_BIN }}.exe ./dist/${{ env.RELEASE_BIN }}.exe
-          7z a -ttar -so -an ./dist | 7z a -si ./${{ env.RELEASE_DIR }}/${{ env.RELEASE_BIN }}-${{ steps.get_version.outputs.version }}-${{ env.WINDOWS_TARGET }}.tar.gz
+        run: mv ./target/${{ matrix.target }}/release/${{ env.RELEASE_BIN }}.exe ./dist/${{ env.RELEASE_BIN }}.exe
 
       - name: Create build keychain (MacOS)
         if: matrix.build == 'macos'
@@ -247,10 +217,10 @@ jobs:
           echo "::debug::Notarization timed out after $RETRY_MINUTES minutes."
           exit 1
 
-      - name: Create tarball (MacOS)
-        if: matrix.build == 'macos'
+      - name: Create Tarball
+        shell: bash
         run: |
-          7z a -ttar -so -an ./dist | 7z a -si ./${{ env.RELEASE_DIR }}/${{ env.RELEASE_BIN }}-${{ steps.get_version.outputs.version }}-${{ env.MACOS_TARGET }}.tar.gz
+          7z a -ttar -so -an ./dist | 7z a -si ./${{ env.RELEASE_DIR }}/${{ env.RELEASE_BIN }}-${{ steps.get_version.outputs.version }}-${{ matrix.target }}.tar.gz
 
       - name: Upload Tarball
         uses: actions/upload-artifact@v2
@@ -276,8 +246,8 @@ jobs:
       - name: Unzip binaries
         shell: bash
         run: |
-          tar -xzvf ./linux/${{ env.RELEASE_BIN }}-${{ needs.build.outputs.version }}-${{ env.LINUX_GNU_TARGET }}.tar.gz && mv ./dist/${{ env.RELEASE_BIN }} ./linux-gnu-cli && rm -rf dist
-          tar -xzvf ./linux/${{ env.RELEASE_BIN }}-${{ needs.build.outputs.version }}-${{ env.LINUX_MUSL_TARGET }}.tar.gz && mv ./dist/${{ env.RELEASE_BIN }} ./linux-musl-cli && rm -rf dist
+          tar -xzvf ./linux-gnu/${{ env.RELEASE_BIN }}-${{ needs.build.outputs.version }}-${{ env.LINUX_GNU_TARGET }}.tar.gz && mv ./dist/${{ env.RELEASE_BIN }} ./linux-gnu-cli && rm -rf dist
+          tar -xzvf ./linux-musl/${{ env.RELEASE_BIN }}-${{ needs.build.outputs.version }}-${{ env.LINUX_MUSL_TARGET }}.tar.gz && mv ./dist/${{ env.RELEASE_BIN }} ./linux-musl-cli && rm -rf dist
           tar -xzvf ./windows/${{ env.RELEASE_BIN }}-${{ needs.build.outputs.version }}-${{ env.WINDOWS_TARGET }}.tar.gz && mv ./dist/${{ env.RELEASE_BIN }}.exe ./windows-cli.exe && rm -rf dist
           tar -xzvf ./macos/${{ env.RELEASE_BIN }}-${{ needs.build.outputs.version }}-${{ env.MACOS_TARGET }}.tar.gz && mv ./dist/${{ env.RELEASE_BIN }} ./macos-cli && rm -rf dist
 
@@ -285,10 +255,40 @@ jobs:
         id: get_shas
         shell: bash
         run: |
-          echo ::set-output name=linux-gnu-sha::"$(sha256sum -b linux-gnu-cli | cut -d ' ' -f1)"
-          echo ::set-output name=linux-musl-sha::"$(sha256sum -b linux-musl-cli | cut -d ' ' -f1)"
-          echo ::set-output name=windows-sha::"$(sha256sum -b windows-cli.exe | cut -d ' ' -f1)"
-          echo ::set-output name=macos-sha::"$(sha256sum -b macos-cli | cut -d ' ' -f1)"
+          LINUX_GNU_SHA="$(sha256sum -b linux-gnu-cli | cut -d ' ' -f1)"
+          LINUX_MUSL_SHA="$(sha256sum -b linux-musl-cli | cut -d ' ' -f1)"
+          WINDOWS_SHA="$(sha256sum -b windows-cli.exe | cut -d ' ' -f1)"
+          MACOS_SHA="$(sha256sum -b macos-cli | cut -d ' ' -f1)"
+          failed=0
+          if [ ${#LINUX_GNU_SHA} -ne 64 ]; then
+            ((failed=$failed+1))
+            echo "::debug::\$LINUX_GNU_SHA has not been computed."
+          fi
+
+          if [ ${#LINUX_MUSL_SHA} -ne 64 ]; then
+            ((failed=$failed+1))
+            echo "::debug::\$LINUX_MUSL_SHA has not been computed."
+          fi
+
+          if [ ${#WINDOWS_SHA} -ne 64 ]; then
+            ((failed=$failed+1))
+            echo "::debug::\$WINDOWS_SHA has not been computed."
+          fi
+
+          if [ ${#MACOS_SHA} -ne 64 ]; then
+            ((failed=$failed+1))
+            echo "::debug::\$MACOS_SHA has not been computed."
+          fi
+
+          if [ "$failed" -gt 0 ]; then
+            echo "::debug::Failed to compute $failed checksum(s)."
+            exit 1
+          fi
+          
+          echo ::set-output name=linux-gnu-sha::"$LINUX_GNU_SHA"
+          echo ::set-output name=linux-musl-sha::"$LINUX_MUSL_SHA"
+          echo ::set-output name=windows-sha::"$WINDOWS_SHA"
+          echo ::set-output name=macos-sha::"$MACOS_SHA"
 
       - name: Create Release
         id: create_release
@@ -300,9 +300,7 @@ jobs:
           release_name: ${{ needs.build.outputs.version }}
           prerelease: ${{ env.is-prerelease }}
           body: |
-            <!---
-              paste the changelog entry here!
-            -->
+            <!-- changelog -->
             ---
             This release was automatically created by [Github Actions](./.github/workflows/release.yml).
 
